# update PKGBUILD and package related files
# to this repo's master branch
sudo: false
env:
  - secure: "SBQZ7Hw1QzETsCEU9ea1590BhttjpKOY8MVLcv8uy7Dw0peGoNODcwpEIb9QcHfUKUfBfBwJv0Vc6G128tO52iT0hqr1bQZeusJHpA1pBAI/gX/lIe63OFXrrvfthv7T2ErnHoSY1hnBVfPKSxCscmSwNZHanRHWZVIuOlYGXpe50x0UTNspplLYYu6u2wYxEvmkLObIDlOPi6m/L3StX/Og3+AcI2R8yCLqncGT1abJsmG8OGCA7nDo9Cq+Fb6n5gtk29WAUJEiT1b0yyifnwI9HRFbBySNo+VYAErL1e9dQj5EFecyCtuc+cOWWQ9V1IezRYPFw8bsd1tADg9CXr9f1+n6DROCex6Cw/RopHPOHI3Fgi0MXilf89nqScSpm9GDFJorGoM5Nw+M8hZECANoAFz2TnUUNI412fTmg/hMgkpU4bJkfz5xNPiy0x7uiLzB2IxATNdrmKPtI7i1o3IltuvmsimFgs/4ZYmTJFcDX5I5Imp+cTIX008wNtAWmpILhMuNcKicWVJQ9Pr6rO18RWWvxT7DHx6N7FBUw83+GpWT5F2YFDWqp7EYxLMkHmdMcwZyr3xyh7qK6m+dS5Thj1G3emODebBDrywBqS5DIVH0/HXExJGHJ5TUuA8ahkrq+2XMQGIn8GLZYsY5LJN1Irh0DLVetQa0OdYpwFQ="
branches:
  only:
    - release
install:
    - true
script:
  - git fetch origin master:master
  - git checkout master
  - ./build.sh
before_deploy:
  - ./before_deploy.sh
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "pkg/kreogist-mu-resource.tar.gz"
  skip_cleanup: true
  on:
    branch: release
