# update PKGBUILD and package related files
# to this repo's master branch
sudo: false
env:
  - secure: "iqZ2JgOVG+tHsQ98fgs7CKGwBpuSgUU4SrTEYpWMdfKsHBivGtfSaHYPIxlhBrDlmuTon5o0ZSyLAsJpgP/m5qvDXwRrrAfSQC/ue9UmzuZkP5+pF3sI+AN0BZeKbU1CbUyK7Fx7lK7dgUPrVt/N/1VtBWux+yUHN9dEEe80gkItwD85kDSLlwQHw03WSJ/2R5mcU7iMuQpK+vEvx9xTsCSBLqxoy9sSzFuaCfmwSYf9IQlhHYu+JZFK64+g3o36Y7gKVxIxM2+Li540d9Ol703RJiFFBta+d4fQ0eAw51ScbOYLtk7cR+2UiPdX/n1KDnXrkR3oUsbP7zX30CU8j+eKjE3arQ0KOcaPjODJbUIARDljO4DcV4LWhNRZsmi2hLlY8f2hc/nZKKT3CToNSpvTnGl2i3wHrZQoLx8TFCixM4eEnJezJFZDRjQu1Kmm+4IEQzWVy7D12FpDy6Et+K0gA12kGh8uxKpKYJpem6/KMlinNDO9ZNo3wyBk/Vx6hi9nF9IJDRNyQOKO7d5C4Wkrlecp1ERT+5IUhHJ8kztj/gZ4zdjkRNi1u7t3/m4jQwb2TlyMoQWlWev5l0PK+Q/EW2swt/cLsYTJL2P9CJx8NvTWJE4DR9SCqtTexAEIqCVfdQWZNj3pUZBV8vu5Pi78VNnUM8M7/sbgoGK9vRA="
branches:
  only:
    - release
install:
    - true
script:
  - git fetch origin master:master
  - git checkout master
  - ./build.sh
before_deploy:
  - ./before_deploy.sh
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "pkg/kreogist-mu-resource.tar.gz"
  skip_cleanup: true
  on:
    branch: release

