# update PKGBUILD and package related files
# to this repo's master branch
sudo: false
branches:
  only:
    - release
install:
    - true
script:
  - git fetch origin master:master
  - git checkout master
  - ./build.sh
before_deploy:
  - ./before_deploy.sh
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "pkg/kreogist-mu-resource.tar.gz"
  skip_cleanup: true
  on:
    branch: release
